openapi: 3.0.3
info:
  title: Library API
  version: 1.0.0
  description: PROG3-TD1-STD22089-RAZAFINDRAKOTO Andy Avotiana
servers:
  - url: https://library.com
paths:
  /books:
    get:
      summary: Get all books
      description: The returned books are ordered by updated datetime.
      operationId: getBooks
      parameters:
        - in: query
          name: bookName
          description: Filter return books by given name
          required: false
          schema:
            type: string
        - in: query
          name: bookReleaseMin
          description: |
            If  `releaseDateMax` is not provided, `releaseDateMin` is ignored.
            `releaseDateMin` can not be after `releaseDateMax`.
          required: false
          schema:
            type: string
            format: date
        - in: query
          name: bookReleaseMax
          description: |
            If  `releaseDateMin` is not provided, `releaseDateMax` is ignored.
            `releaseDateMax` can not be before `releaseDateMax`.
          required: false
          schema:
            type: string
            format: date        
      responses:
        200:
          description: The list of filtered books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
    put:
      summary: Create or update a list of books
      operationId: crupdateBooks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Book"
      responses:
        200:
          description: The list of created or updated books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
  /authors:
    get:
      summary: Get all authors
      description: The returned authors are filtered by naùe
      operationId: getAuthors
      parameters:
        - in: query
          name: authorName
          description: return authors by given name
          required: false
          schema:
            type: string
      responses:
        200:
          description: list of filtered authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Author"

    put:
      summary: Create or update a list of authors
      operationId: crupdateAuthors
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Author"
      responses:
        200:
          description: list of created or updated authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Author"


    delete:
      summary: Delete all authors
      operationId: deleteAllAuhtors
      parameters:
        - in: query
          name: allAuthors
          description: describe all authors to be deleted
          required: true
          schema:
            type: string
      responses:
        200:
          description: All authors deleted successfully

  /authors/{authorId}:
    delete:
      summary: Delete an author
      operationId: deleteAuthor
      parameters:
        - in: path
          name: authorId
          description: author Id to be deleted
          required: true
          schema:
            type: string
      responses:
        "200":
          description: author deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
        bookName:
          type: string
        author:
          $ref: '#/components/schemas/Author'
        pageNumbers:
          type: integer
        topic:
          type: string
          enum:
            - ROMANCE
            - COMEDY
            - OTHER
        releaseDate:
          type: string
          format: date

    Author:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        sex:
          $ref: '#/components/schemas/Sex'
        
    Sex:
      type: string
      format: char
      enum:
        - M
        - F
